---
dist: xenial

branches:
  only:
  - master

language: python
python: "2.7"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq software-properties-common
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update
- sudo apt-get install -y ansible
- sudo ansible-galaxy install grycap.docker
- sudo ansible-galaxy install geerlingguy.ntp

script:
  - sudo ln -s ${PWD} /etc/ansible/roles/role_under_test
  # Ansible syntax check.
  - 'sudo ansible-playbook tests/test.yml --syntax-check'

  # Test role installation.
  - 'sudo useradd munge'
  - 'sudo mkdir -p /etc/munge'
  - 'sudo touch /etc/munge/munge.key'
  - 'sudo mkdir -p /mnt/export && sudo chmod 777 /mnt/export'
  - 'sudo ansible-playbook tests/test.yml -e galaxy_lrms=slurm'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
