---
branches:
  only:
  - master

language: python
python: "2.7"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq software-properties-common
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update
- sudo apt-get install -y ansible

script:
  # Ansible syntax check.
  - 'ansible-playbook tests/test.yml --syntax-check'

  # Test role installation.
  - 'ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
